version: '3.8'

services:
  # seq:
  #   image: datalust/seq:latest
  #   restart: 'no'
  #   ports:
  #     - '5380:80'
  #     - '5341:5341'
  #   environment:
  #     - ACCEPT_EULA=Y
  #   volumes:
  #     - seq-data:/data

  # jaeger:
  #   image: jaegertracing/all-in-one:1.34
  #   restart: 'no'
  #   ports:
  #     - '6831:6831/udp'
  #     - '16686:16686'

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: 'no'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssword
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  # seq-data:
  sql-data:
