// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: pb/job-state.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobStateServiceClient is the client API for JobStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobStateServiceClient interface {
	CreateJobState(ctx context.Context, in *CreateJobStateRequest, opts ...grpc.CallOption) (*CreateJobStateResponse, error)
}

type jobStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobStateServiceClient(cc grpc.ClientConnInterface) JobStateServiceClient {
	return &jobStateServiceClient{cc}
}

func (c *jobStateServiceClient) CreateJobState(ctx context.Context, in *CreateJobStateRequest, opts ...grpc.CallOption) (*CreateJobStateResponse, error) {
	out := new(CreateJobStateResponse)
	err := c.cc.Invoke(ctx, "/JobStateService/CreateJobState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobStateServiceServer is the server API for JobStateService service.
// All implementations must embed UnimplementedJobStateServiceServer
// for forward compatibility
type JobStateServiceServer interface {
	CreateJobState(context.Context, *CreateJobStateRequest) (*CreateJobStateResponse, error)
	mustEmbedUnimplementedJobStateServiceServer()
}

// UnimplementedJobStateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobStateServiceServer struct {
}

func (UnimplementedJobStateServiceServer) CreateJobState(context.Context, *CreateJobStateRequest) (*CreateJobStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJobState not implemented")
}
func (UnimplementedJobStateServiceServer) mustEmbedUnimplementedJobStateServiceServer() {}

// UnsafeJobStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobStateServiceServer will
// result in compilation errors.
type UnsafeJobStateServiceServer interface {
	mustEmbedUnimplementedJobStateServiceServer()
}

func RegisterJobStateServiceServer(s grpc.ServiceRegistrar, srv JobStateServiceServer) {
	s.RegisterService(&JobStateService_ServiceDesc, srv)
}

func _JobStateService_CreateJobState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStateServiceServer).CreateJobState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JobStateService/CreateJobState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStateServiceServer).CreateJobState(ctx, req.(*CreateJobStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobStateService_ServiceDesc is the grpc.ServiceDesc for JobStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JobStateService",
	HandlerType: (*JobStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJobState",
			Handler:    _JobStateService_CreateJobState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/job-state.proto",
}
