// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: pb/job-state.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStateModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *JobStateModel) Reset() {
	*x = JobStateModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_job_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStateModel) ProtoMessage() {}

func (x *JobStateModel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_job_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStateModel.ProtoReflect.Descriptor instead.
func (*JobStateModel) Descriptor() ([]byte, []int) {
	return file_pb_job_state_proto_rawDescGZIP(), []int{0}
}

func (x *JobStateModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobStateModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobStateModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateJobStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *CreateJobStateRequest) Reset() {
	*x = CreateJobStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_job_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobStateRequest) ProtoMessage() {}

func (x *CreateJobStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_job_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobStateRequest.ProtoReflect.Descriptor instead.
func (*CreateJobStateRequest) Descriptor() ([]byte, []int) {
	return file_pb_job_state_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobStateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateJobStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobState *JobStateModel `protobuf:"bytes,1,opt,name=job_state,json=jobState,proto3" json:"job_state,omitempty"`
}

func (x *CreateJobStateResponse) Reset() {
	*x = CreateJobStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_job_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobStateResponse) ProtoMessage() {}

func (x *CreateJobStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_job_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobStateResponse.ProtoReflect.Descriptor instead.
func (*CreateJobStateResponse) Descriptor() ([]byte, []int) {
	return file_pb_job_state_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobStateResponse) GetJobState() *JobStateModel {
	if x != nil {
		return x.JobState
	}
	return nil
}

var File_pb_job_state_proto protoreflect.FileDescriptor

var file_pb_job_state_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0d, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x6a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x32, 0x56, 0x0a, 0x0f, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x6b, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x69, 0x65, 0x72, 0x72, 0x61, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_job_state_proto_rawDescOnce sync.Once
	file_pb_job_state_proto_rawDescData = file_pb_job_state_proto_rawDesc
)

func file_pb_job_state_proto_rawDescGZIP() []byte {
	file_pb_job_state_proto_rawDescOnce.Do(func() {
		file_pb_job_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_job_state_proto_rawDescData)
	})
	return file_pb_job_state_proto_rawDescData
}

var file_pb_job_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_job_state_proto_goTypes = []interface{}{
	(*JobStateModel)(nil),          // 0: JobStateModel
	(*CreateJobStateRequest)(nil),  // 1: CreateJobStateRequest
	(*CreateJobStateResponse)(nil), // 2: CreateJobStateResponse
}
var file_pb_job_state_proto_depIdxs = []int32{
	0, // 0: CreateJobStateResponse.job_state:type_name -> JobStateModel
	1, // 1: JobStateService.CreateJobState:input_type -> CreateJobStateRequest
	2, // 2: JobStateService.CreateJobState:output_type -> CreateJobStateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_job_state_proto_init() }
func file_pb_job_state_proto_init() {
	if File_pb_job_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_job_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStateModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_job_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJobStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_job_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJobStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_job_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_job_state_proto_goTypes,
		DependencyIndexes: file_pb_job_state_proto_depIdxs,
		MessageInfos:      file_pb_job_state_proto_msgTypes,
	}.Build()
	File_pb_job_state_proto = out.File
	file_pb_job_state_proto_rawDesc = nil
	file_pb_job_state_proto_goTypes = nil
	file_pb_job_state_proto_depIdxs = nil
}
